const twColors = require("tailwindcss/colors");

module.exports = {
  transparent: "transparent",
  current: "currentColor",
  white: twColors.white,
  black: twColors.black,
  grey: {
    50: twColors.neutral[50],
    100: twColors.neutral[100],
    200: twColors.neutral[200],
    300: twColors.neutral[300],
    400: twColors.neutral[400],
    500: twColors.neutral[500],
    600: twColors.neutral[600],
    700: twColors.neutral[700],
    800: twColors.neutral[800],
    900: twColors.neutral[900],
    950: twColors.neutral[950],
  },
  stone: {
    50: twColors.stone[50],
    100: twColors.stone[100],
    200: twColors.stone[200],
    300: twColors.stone[300],
    400: twColors.stone[400],
    500: twColors.stone[500],
    600: twColors.stone[600],
    700: twColors.stone[700],
    800: twColors.stone[800],
    900: twColors.stone[900],
    light: twColors.stone[700],
    base: twColors.stone[800],
    faded: "#363330",
    text: "#78716C",
  },
  habitColors: {
    stone: {
      light: twColors.stone[700],
      base: twColors.stone[800],
      faded: "#363330",
      text: "#78716C",
    },
    red: {
      light: twColors.red[100],
      base: twColors.red[400],
      faded: "#F0C9C9",
      text: "#CDA4A4",
    },
    orange: {
      light: twColors.orange[100],
      base: twColors.orange[400],
      faded: "#F0DBBE",
      text: "#D1BCA0",
    },
    amber: {
      light: twColors.amber[100],
      base: twColors.amber[400],
      faded: "#EEE2B0",
      text: "#CEC6A3",
    },
    yellow: {
      light: twColors.yellow[100],
      base: twColors.yellow[400],
      faded: "#F0EBAE",
      text: "#CBC799",
    },
    lime: {
      light: twColors.lime[100],
      base: twColors.lime[400],
      faded: "#DCF0B3",
      text: "#BDCF99",
    },
    green: {
      light: twColors.green[100],
      base: twColors.green[400],
      faded: "#C1F0D1",
      text: "#96C9A7",
    },
    emerald: {
      light: twColors.emerald[100],
      base: twColors.emerald[400],
      faded: "#B8EED2",
      text: "#9BCBB2",
    },
    teal: {
      light: twColors.teal[100],
      base: twColors.teal[400],
      faded: "#BEECE2",
      text: "#96C3B9",
    },
    cyan: {
      light: twColors.cyan[100],
      base: twColors.cyan[400],
      faded: "#C1EAEE",
      text: "#96C0C4",
    },
    sky: {
      light: twColors.sky[100],
      base: twColors.sky[400],
      faded: "#C6DFEF",
      text: "#98B5C8",
    },
    blue: {
      light: twColors.blue[100],
      base: twColors.blue[400],
      faded: "#C7D9F2",
      text: "#A2B5CD",
    },
    indigo: {
      light: twColors.indigo[100],
      base: twColors.indigo[400],
      faded: "#C9D2F4",
      text: "#A5AED0",
    },
    violet: {
      light: twColors.violet[100],
      base: twColors.violet[400],
      faded: "#D7D0F7",
      text: "#B2AAD3",
    },
    purple: {
      light: twColors.purple[100],
      base: twColors.purple[400],
      faded: "#E1CDF7",
      text: "#B5A0CD",
    },
    fuchsia: {
      light: twColors.fuchsia[100],
      base: twColors.fuchsia[400],
      faded: "#EFD0F7",
      text: "#C6A3CF",
    },
    pink: {
      light: twColors.pink[100],
      base: twColors.pink[400],
      faded: "#F5D0E5",
      text: "#D0A4BD",
    },
    rose: {
      light: twColors.rose[100],
      base: twColors.rose[400],
      faded: "#F3CED1",
      text: "#D2A3A6",
    },
  },
};
