import {
  Accessibility,
  Activity,
  Airplay,
  AlarmClock,
  AlarmClockCheck,
  AlarmClockMinus,
  AlarmClockOff,
  AlarmClockPlus,
  Apple,
  Award,
  Bandage,
  Bell,
  BellDot,
  BellMinus,
  BellOff,
  BellPlus,
  BellRing,
  Book,
  BookCheck,
  BookHeart,
  BookMarked,
  Brain,
  BrainCircuit,
  BrainCog,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarPlus,
  CalendarRange,
  CalendarSearch,
  CalendarX,
  Camera,
  ChartBar,
  ChartBarDecreasing,
  ChartBarIncreasing,
  ChartLine,
  ChartPie,
  Check,
  CircleCheck,
  CirclePlus,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Clock,
  ClockArrowDown,
  ClockArrowUp,
  Cloud,
  CloudSun,
  Coffee,
  Compass,
  Computer,
  Diamond,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dna,
  Dumbbell,
  Ear,
  Eye,
  EyeOff,
  Fish,
  Flame,
  Flashlight,
  Flower,
  Focus,
  GlassWater,
  HandHeart,
  Heart,
  HeartPulse,
  Hourglass,
  Lamp,
  Leaf,
  Lightbulb,
  Lock,
  LockOpen,
  MapPin,
  Medal,
  Microchip,
  Microscope,
  Music,
  Notebook,
  PawPrint,
  Pen,
  PersonStanding,
  Pill,
  Puzzle,
  Rabbit,
  Recycle,
  Rocket,
  Scale,
  Shield,
  Smartphone,
  Smile,
  Sprout,
  Star,
  Sun,
  Syringe,
  Target,
  TestTube,
  Thermometer,
  Timer,
  TreeDeciduous,
  Trophy,
  Umbrella,
  Utensils,
  Wifi,
  Zap,
} from 'lucide-react-native';

export const habitIcons = {
  accessibility: Accessibility,
  activity: Activity,
  airplay: Airplay,
  alarmClock: AlarmClock,
  alarmClockCheck: AlarmClockCheck,
  alarmClockMinus: AlarmClockMinus,
  alarmClockOff: AlarmClockOff,
  alarmClockPlus: AlarmClockPlus,
  apple: Apple,
  award: Award,
  bandage: Bandage,
  bell: Bell,
  bellDot: BellDot,
  bellMinus: BellMinus,
  bellOff: BellOff,
  bellPlus: BellPlus,
  bellRing: BellRing,
  book: Book,
  bookCheck: BookCheck,
  bookHeart: BookHeart,
  bookMarked: BookMarked,
  brain: Brain,
  brainCircuit: BrainCircuit,
  brainCog: BrainCog,
  calendar: Calendar,
  calendarCheck: CalendarCheck,
  calendarClock: CalendarClock,
  calendarPlus: CalendarPlus,
  calendarRange: CalendarRange,
  calendarSearch: CalendarSearch,
  calendarX: CalendarX,
  camera: Camera,
  chartBar: ChartBar,
  chartBarDecreasing: ChartBarDecreasing,
  chartBarIncreasing: ChartBarIncreasing,
  chartLine: ChartLine,
  chartPie: ChartPie,
  check: Check,
  circleCheck: CircleCheck,
  circlePlus: CirclePlus,
  circleX: CircleX,
  clipboard: Clipboard,
  clipboardCheck: ClipboardCheck,
  clipboardList: ClipboardList,
  clipboardPlus: ClipboardPlus,
  clock: Clock,
  clockArrowDown: ClockArrowDown,
  clockArrowUp: ClockArrowUp,
  cloud: Cloud,
  cloudSun: CloudSun,
  coffee: Coffee,
  compass: Compass,
  computer: Computer,
  diamond: Diamond,
  dice1: Dice1,
  dice2: Dice2,
  dice3: Dice3,
  dice4: Dice4,
  dice5: Dice5,
  dice6: Dice6,
  dna: Dna,
  dumbbell: Dumbbell,
  ear: Ear,
  eye: Eye,
  eyeOff: EyeOff,
  fish: Fish,
  flame: Flame,
  flashlight: Flashlight,
  flower: Flower,
  focus: Focus,
  glassWater: GlassWater,
  handHeart: HandHeart,
  heart: Heart,
  heartPulse: HeartPulse,
  hourglass: Hourglass,
  lamp: Lamp,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  lockOpen: LockOpen,
  mapPin: MapPin,
  medal: Medal,
  microchip: Microchip,
  microscope: Microscope,
  music: Music,
  notebook: Notebook,
  pawPrint: PawPrint,
  pen: Pen,
  personStanding: PersonStanding,
  pill: Pill,
  puzzle: Puzzle,
  rabbit: Rabbit,
  recycle: Recycle,
  rocket: Rocket,
  scale: Scale,
  shield: Shield,
  smartphone: Smartphone,
  smile: Smile,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  testTube: TestTube,
  thermometer: Thermometer,
  timer: Timer,
  treeDeciduous: TreeDeciduous,
  trophy: Trophy,
  umbrella: Umbrella,
  utensils: Utensils,
  wifi: Wifi,
  zap: Zap,
} as const;

export function HabitIcon({
  icon,
  ...props
}: {
  icon: keyof typeof habitIcons;
} & React.ComponentProps<(typeof habitIcons)[keyof typeof habitIcons]>) {
  const Icon = habitIcons[icon];
  return <Icon {...props} />;
}
